language: node_js

node_js:
  - "0.12"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g spacejam
  - meteor npm install

script:
  - spacejam test --once --driver-package=practicalmeteor:mocha-console-runner
  - meteor build $HOME/build.tgz
